metadata.format.version = "1.1"

[versions]

velocity = "3.4.0-SNAPSHOT"
paper = "1.21.8-R0.1-SNAPSHOT"
sponge = "14.0.0"
blossom = "2.1.0"
shadow = "9.1.0"
miniplaceholders = "3.0.1"
libertybans = "1.1.0"

[libraries]

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
sponge = { module = "org.spongepowered:spongeapi", version.ref = "sponge" }
adventure-api = { group = "net.kyori", name = "adventure-api", version = "4.24.0" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version = "4.13.1" }
libertybans = { group = "space.arim.libertybans", name = "bans-api", version.ref = "libertybans" }
caffeine = "com.github.ben-manes.caffeine:caffeine:3.2.2"

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
